# Generated by Django 4.0 on 2022-01-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_organization', models.CharField(max_length=100)),
                ('opening_date', models.DateField()),
                ('capital', models.FloatField()),
                ('ceo_of_company', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=500)),
                ('cards', models.CharField(max_length=300)),
                ('number_of_branches', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('affiliated_companies', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
