# Generated by Django 4.0 on 2022-01-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_of_or', models.CharField(max_length=100)),
                ('op_dt', models.DateField()),
                ('capital', models.CharField(max_length=100)),
                ('ceo_of_cmp', models.CharField(max_length=100)),
                ('ser_es', models.CharField(max_length=500)),
                ('cards', models.CharField(max_length=300)),
                ('n_of_br', models.IntegerField()),
                ('n_of_emp', models.IntegerField()),
                ('aff_com', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
