# Generated by Django 4.0 on 2022-01-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_banks_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=60)),
                ('language', models.CharField(choices=[('ru', 'ru'), ('uz', 'uz'), ('en', 'en')], max_length=10)),
                ('cource', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('gpa', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
